environment:
  matrix:
    - nodejs_version: "8.11.3"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - if "%nodejs_version%" == "8.11.3" (
      npm run lint &&
      npm run coverage  &&
      npm run test-doclint &&
      npm run test-types
    )
