environment:
  matrix:
    - nodejs_version: "6.12.3"
    - nodejs_version: "10.6.0"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - if "%nodejs_version%" == "10.6.0" (
      npm run lint &&
      npm run coverage  &&
      npm run test-doclint
    ) else (
      npm run unit-node6
    )
