environment:
  matrix:
    - nodejs_version: "10.18.1"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - if "%nodejs_version%" == "10.18.1" (
      npm run lint &&
      npm run coverage  &&
      npm run test-doclint &&
      npm run test-types
    )
