language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'if [ "$NODE8" = "true" ]; then cd experimental/puppeteer-firefox && npm i && cd ../..; fi'
script:
  - 'if [ "$NODE8" = "true" ]; then npm run lint; fi'
  - 'if [ "$NODE8" = "true" ]; then npm run coverage; fi'
  - 'if [ "$NODE8" = "true" ]; then npm run funit; fi'
  - 'if [ "$NODE8" = "true" ]; then npm run test-doclint; fi'
  - 'if [ "$NODE8" = "true" ]; then npm run test-types; fi'
  - 'if [ "$NODE8" = "true" ]; then npm run bundle; fi'
  - 'if [ "$NODE8" = "true" ]; then npm run unit-bundle; fi'
  - 'if [ "$NODE6" = "true" ]; then npm run unit-node6; fi'
jobs:
  include:
    - node_js: "8.11.3"
      env: NODE8=true
    - node_js: "6.12.3"
      env: NODE6=true
before_deploy: "npm run apply-next-version"
deploy:
  provider: npm
  email: aslushnikov@gmail.com
  api_key:
    secure: YCunawHmZTJQw2paGA+DrkZAWuDwD5r7RWr1HahLAIG53O+KYN12S41Fk8aon8zMIdWo0rtwoCNf+efvjFb2dDYdx8mikr9hBngx8yMdOGtwyvOPShcoWVwJsESOGpmN2Utb7eRaJGGCTeYxm6zT6i8yQd6E0Myh99iSfSCsYeohgVrLLBOpx8luqLHTKCD0rnwR6OJojcU1pvpFi/kHeqPbrwHoSX8/xuaEfWtWgDHZnkRv2utolr4Dud5VnO6xYY5trIUts5YRHcaEU69Sb8Vgeaks2GcQ0mcubqHqDY5va+eZnWSD7uMzkaN/JbHS7Ak41/GRSJjD/OA6apgz+3G5z7karUop5fAuxCLS+E4ZqTWEGO8uQZOnDmvFaMQdPiBc04g75fR71TvwMhCvVHjSAJP3+qw4pyYoezPFANVR4/IKVDhioKlYh/dU7Y5dTGgpCK72wN4ARo4EIThcxOLla/3c1rzebcC5AbDSU5TPEV0Ewnp9Y0yOo3ZajjJxWGolOXKE6JZXr3Zmryu1ULLtsWpLSBC8W+5QOBbwAWY3vC3ELt21k2O7dYyVkMlNIDGfHxh03d5Z+nNggDuMRUA4S8cFDW5ROSLYq3k4xvbQOeiNdX6wA1KHizG2TnBb00fy+GizwEDZ2pKwvrr0pQ9HI+kjAmTJzqyfatrQtfw=
  on:
    branch: master
    condition: "$NODE8 = true"
  skip_cleanup: true
  tag: next
