language: node_js
services: xvfb

jobs:
  include:

    # Runs unit tests on OSX + Chromium
    - os: "osx"
      node_js: "10.19.0"
      env:
        - CHROMIUM=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - ls .local-chromium .local-firefox
        - npm run tsc
        - npm run unit

    # Runs unit tests on Windows + Chromium
    - os: "windows"
      node_js: "10.19.0"
      env:
        - CHROMIUM=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - ls .local-chromium .local-firefox
        - npm run tsc
        - travis_retry npm run unit

    # Runs unit tests on Linux + Chromium
    - node_js: "10.19.0"
      env:
        - CHROMIUM=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - npm run test-install
        - npm run coverage

    # This bot runs all the extra checks that aren't the main Puppeteer unit tests
    - node_js: "10.19.0"
      env:
        -CHROMIUM=true
      script:
        - npm run test-install
        - npm run lint
        - npm run test-doclint
        - npm run test-types

    # Runs unit tests on Linux + Firefox
    - node_js: "10.19.0"
      env:
        - FIREFOX=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - npm run funit

notifications:
  email: false
