language: node_js
node_js:
  - "7"
  - "8"
dist: trusty
env:
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  # puppeteer's install script downloads Chrome
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xvfb to boot
script:
  - yarn run lint
  - yarn run test-puppeteer
  - yarn run test-phantom
