language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - 'if [ "$NODE7" = "true" ]; then npm run lint; fi'
  - 'if [ "$NODE7" = "true" ]; then npm run coverage; fi'
  - 'if [ "$NODE7" = "true" ]; then npm run test-doclint; fi'
  - 'if [ "$NODE6" = "true" ]; then npm run unit-node6; fi'
jobs:
  include:
    - node_js: "7.10.1"
      env: NODE7=true
    - node_js: "6.12.3"
      env: NODE6=true
before_deploy: "npm run apply-next-version"
deploy:
  provider: npm
  email: aslushnikov@gmail.com
  api_key:
    secure: 6kP1uXKwrnJYeqVJOz/JTT7UCdsAOlbdl56VWHqBQnld0iXpVwVCJDfkqIyyYZhnv2UNgDCcVMiC6U/rJUwuOQKVlwzwqQremQXsFxRI9+bHZq/cOpXuDT3ey9BJS5zumE2siMqvIdz9N3FTC5oBEyw6odrxCZEnnsnzSCZpsBHrx+7M+pepSfCfjZgriPvuFmTSed20uYb0u07DxzTd49DaFW87KD9p4oI6OkDPpFRDH7CjAcPzaS3KUfiOq7Axa4Vy73eunQADAXMi17lEq02oPCzaCUCfOa1elPd10O4jQNmIhJcqwb9BXW/TN0oJpH9h1RGGwOMIFnJiQ1mQR+cySxESYI6JmW8Fh6OawHdHcNz5Zn7Xyc20SAmhIhOs/WJbdsULHnJibgvZZr6X9o+rybZbqOn7PvX1BmLxb63r7TcFvUYoMuP+PNKJulMHvdn4eVXKxEE62SwkpjItyUVSzDl7HGhjSBlnvB8YIaUULuyE28nPKzhWG2R++h562ZhclWm7Nanad/u/Q07ua9T3toC8Sr2BYkSTXn+0gdb0Lbt5ESETd1MuWcW4tAGdaL7mSdCSBQ/cth2YnCfCl/SxrlnfWM/dwVTMtlE9gvK4Ppn6f8n+DGh0yUHrNeHV1uoTA3efNbPc/U9F9reak3uvJFyy1Ue4l2d/vJ6PnzE=
  on:
    branch: master
    condition: "$NODE7 = true"
  skip_cleanup: true
  tag: next
