language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  # puppeteer's install script downloads Chrome
script:
  - 'if [ ${NODE6} != "true"]; then yarn run lint; fi'
  - 'if [ ${NODE6} != "true"]; then yarn run coverage; fi'
  - 'if [ ${NODE6} != "true"]; then yarn run test-phantom; fi'
  - yarn run node6
  - yarn run test-node6
  - yarn run sanity
jobs:
  include:
    - node_js: "7"
    - node_js: "6.4.0"
      env: NODE6=true