language: node_js
node_js:
  - "7"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
env:
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  # puppeteer's install script downloads Chrome
script:
  - yarn run lint
  - yarn run unit
  - yarn run test-phantom
