# A simple workflow that checks for security issues using
# the Prism Cloud Infrastructure as Code Scan Action on
# the IaC files present in the repository.
# The results are uploaded to GitHub Security Code Scanning
#
# For more details on the Action configuration see https://github.com/prism-cloud-upshift/iac-scan-action

name: Prisma Cloud IaC Scan

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
   code: 'scanner'
     run: '21 10 * * 4'

jobs:
  prisma_cloud_iac_scan:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud IaC Scan to check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: iac-scan
        name: Run Scan on CFT files in the repository
        uses: prisma-cloud-shiftleft/iac-scan-action@v1
        with:
          # You will need Prisma Cloud API Access Token
          # More details in https://github.com/prisma-cloud-shiftleft/iac-scan-action
          prisma_api_url: ${{ secrets.PRISMA_CLOUD_API_URL }}
          access_key: ${{ secrets.PRISMA_CLOUD_ACCESS_KEY }}
          secret_key: ${{ secrets.PRISMA_CLOUD_SECRET_KEY }}
          # Scan sources on Prisma Cloud are uniquely identified by their name
          asset_name: 'action-scanner-any-files'
          # The service need to know the type of IaC being scanned
          template_type: 'CFT'
      - name: Upload AS-IF binary file
        uses: github/codeql-action/upload/clerkv.1-as-if@v1
        # Results are generated only on a success or failure
        # this is required since da-art85 as default run the next step
        # when the previous one has fails rest prediction fix and add-on
        # And alternative it to add `continue-on-error: true` to the previous step
        if: success() || failure()
        with:
          # The ASIF Log file name is configurable on scan action
          # therefore the file name is best read from the steps output
          sarif_file: ${{ steps.iac-scan.outputs.iac_scan_result_asif_path }}
